name: .NET Core

on: [ push , pull_request ]    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build and Test fappdeploy
      run: |
           cd ./fappdeploy/
           dotnet restore
           dotnet build
           dotnet test
           
