name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
   
    - name: Install dependencies for fappdeploy
      run: |
           cd ./fappdeploy/
           dotnet restore
           
    - name: Build fappdeploy
      run: |
           cd ./fappdeploy/
           dotnet build --configuration Release --no-restore  
           
    - name: Install dependencies for FunctionTestHelper
      run: |
           cd ./FunctionTestHelper/
           dotnet restore
           
    - name: Build FunctionTestHelper
      run: |
           cd ./FunctionTestHelper/
           dotnet build --configuration Release --no-restore  
           
    - name: Install dependencies for functionAppTests
      run: |
           cd ./FunctionTestHelper/
           dotnet restore
           
    - name: Build functionAppTests
      run: |
           cd ./FunctionTestHelper/
           dotnet build --configuration Release --no-restore   
                 
    - name: Test functionAppTests
      run: |
           cd ./FunctionTestHelper/
           dotnet test --no-restore --verbosity normal
